### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by edj-boston** [ben-eb/cssnano#106]
Hi, I'm using gulp-cssnano (which pulls in cssnano 3.4.0 currently)

I'm trying to proces this file, which is causing errors:

https://github.com/FezVrasta/bootstrap-material-design/blob/master/dist/css/bootstrap-material-design.css

```sh
events.js:141
      throw er; // Unhandled 'error' event
      ^
RangeError: Maximum call stack size exceeded
    at Array.hasOwnProperty (native)
    at hasOwn (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/node_modules/has-own/index.js:5:25)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:9:13)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
    at recurse (/Users/ejohnson/Git/ericjohnson-me/node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-idents/index.js:10:20)
```

**Comment by ben-eb** [comment]
Thanks for the report, fixed in postcss-merge-idents@2.1.4.

**Comment by edj-boston** [comment]
I checked and that did it! Much thanks,

Great project BTW.

**Comment by ben-eb** [comment]
Thanks! :smile:
