### ISSUE TITLE
gulp-cssnano breaks with latest cssnano v3.5.0 when using 'calc()'

### ISSUE THREAD

**Issue by calvinnwq** [ben-eb/cssnano#130]
This is the line that breaks:

`background-position: 0 calc(50% - 3px);`

The error message:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'value' of undefined
    at /node_modules/cssnano/dist/lib/reducePositions.js:72:49
    at Array.forEach (native)
    at transform (/node_modules/cssnano/dist/lib/reducePositions.js:64:14)
    at /node_modules/postcss/lib/container.js:88:34
    at /node_modules/postcss/lib/container.js:73:26
    at Rule.each (/node_modules/postcss/lib/container.js:60:22)
    at Rule.walk (/node_modules/postcss/lib/container.js:72:21)
    at /node_modules/postcss/lib/container.js:76:32
    at Root.each (/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/node_modules/postcss/lib/container.js:72:21)
```

When I uninstall cssnano v3.5.0 and install v3.4.0, the error goes away.

**Comment by ben-eb** [comment]
Does it work with `3.5.1`?

**Comment by calvinnwq** [comment]
@ben-eb just tested and it does work now.

**Comment by ben-eb** [comment]
Awesome. :+1:
