### ISSUE TITLE
Fails to compile after updating.

### ISSUE THREAD

**Issue by DylanPiercey** [ben-eb/cssnano#131]
```console
TypeError: Cannot read property 'constructor' of null
    at clone (/.../node_modules/postcss-merge-rules/dist/lib/clone.js:12:25)
    at clone (/.../node_modules/postcss-merge-rules/dist/lib/clone.js:29:25)
    at clone (/.../node_modules/postcss-merge-rules/dist/lib/clone.js:29:25)
    at /.../node_modules/postcss-merge-rules/dist/lib/clone.js:26:24
```

Although the error is within the rule merge library I am assuming at some point it comes through here as this is the postcss middleware that causes the issue and "merge-rules" hasen't been updated for a while.

**Comment by DylanSale** [comment]
Yep, I'm getting this same issue.

**Comment by fdubost** [comment]
Same issue for me.

**Comment by TrySound** [comment]
Does 3.4 work fine?

**Comment by tomat** [comment]
Not working with 3.4 here either, so probably some other package causing it?

**Comment by fdubost** [comment]
Doesn't work with 3.4 @TrySound :confused:

**Comment by ben-eb** [comment]
Fix is coming shortly.

**Comment by ben-eb** [comment]
Fixed in https://github.com/ben-eb/postcss-merge-rules/commit/d0835cc97eb2243fc4177e7e1ee9f08916cc4405.

**Comment by fdubost** [comment]
I still have the problem :disappointed_relieved: 
```
gulp-cssnano@2.1.1 node_modules/gulp-cssnano
├── object-assign@4.0.1
├── vinyl-sourcemaps-apply@0.2.1 (source-map@0.5.3)
├── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, beeper@1.1.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, fancy-log@1.2.0, vinyl@0.5.3, chalk@1.1.1, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.1, multipipe@0.1.2, dateformat@1.0.12)
└── cssnano@3.5.1 (postcss-normalize-charset@1.1.0, postcss-discard-empty@2.0.1, postcss-minify-gradients@1.0.1, postcss-reduce-transforms@1.0.3, postcss-discard-duplicates@2.0.1, indexes-of@1.0.1, postcss-reduce-idents@2.2.2, postcss-convert-values@2.3.4, postcss-merge-rules@2.0.4, postcss-discard-comments@2.0.4, defined@1.0.0, postcss-value-parser@3.2.3, postcss-ordered-values@2.1.0, decamelize@1.1.2, postcss-filter-plugins@2.0.0, postcss-zindex@2.0.1, postcss-minify-params@1.0.4, postcss-unique-selectors@2.0.2, postcss-discard-unused@2.2.1, postcss-minify-font-values@1.0.2, postcss-merge-longhand@2.0.1, postcss-merge-idents@2.1.5, postcss-calc@5.2.0, postcss-normalize-url@3.0.7, postcss-minify-selectors@2.0.4, postcss-colormin@2.1.8, postcss@5.0.14, postcss-svgo@2.1.1)

...

TypeError: Cannot read property 'constructor' of null
    at cloneNode (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:30:25)
    at cloneNode (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:46:44)
    at cloneNode (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:46:44)
    at /.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:43:24
    at Array.map (native)
    at cloneNode (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:42:31)
    at Rule.clone (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:104:22)
    at Rule.cloneBefore (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/node.js:114:27)
    at partialMerge (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:100:33)
    at /.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:184:17
    at /.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/container.js:115:34
    at /.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/container.js:73:26
    at Root.each (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss/lib/container.js:113:25)
    at /.../node_modules/gulp-cssnano/node_modules/cssnano/node_modules/postcss-merge-rules/dist/index.js:190:13
```

**Comment by ben-eb** [comment]
@fdubost What CSS causes this problem?

**Comment by tomat** [comment]
@fdubost Me too, this seems to solve it for now:

```
"cssnano": "3.4.0",
"postcss-discard-comments": "2.0.3"
```

**Comment by fdubost** [comment]
@ben-eb I don't know, how can I find it ?

**Comment by luhmann** [comment]
@tomat: Thanks for that tip. Removing all the comments from the css that is supposed to be minified actually works for me too.

**Comment by ben-eb** [comment]
@fdubost If you can share your CSS then I can write a test case for this problem and fix it. :smile:

**Comment by fdubost** [comment]
It works with `cssnano({mergeRules: false})`, so I guess that postcss-merge causes the problem.

**Comment by tomat** [comment]
@ben-eb: Narrowed it down to this (note the spaces after `auto`, works with the spaces removed):

```
#foo .bar {
    margin-left: auto ;
    margin-right: auto ;
}
#foo .qux {
    margin-right: auto ;
}
```

Full error:
```
Module build failed: TypeError: Cannot read property 'constructor' of null
    at cloneNode (/Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:30:25)
    at cloneNode (/Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:46:44)
    at cloneNode (/Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:46:44)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:43:24
    at Array.map (native)
    at cloneNode (/Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:42:31)
    at Rule.clone (/Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:104:22)
    at Rule.cloneBefore (/Users/tomat/mfl/mfl/node_modules/postcss/lib/node.js:114:27)
    at partialMerge (/Users/tomat/mfl/mfl/node_modules/postcss-merge-rules/dist/index.js:100:33)
    at /Users/tomat/mfl/mfl/node_modules/postcss-merge-rules/dist/index.js:184:17
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/container.js:115:34
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/container.js:73:26
    at Root.each (/Users/tomat/mfl/mfl/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/Users/tomat/mfl/mfl/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/Users/tomat/mfl/mfl/node_modules/postcss/lib/container.js:113:25)
    at /Users/tomat/mfl/mfl/node_modules/postcss-merge-rules/dist/index.js:190:13
    at LazyResult.run (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:206:20)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:120:37
    at LazyResult.asyncTick (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:134:15)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:134:15)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:134:15)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:134:15)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:134:15)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:134:15)
    at /Users/tomat/mfl/mfl/node_modules/postcss/lib/lazy-result.js:132:27
``

**Comment by ben-eb** [comment]
@tomat Thanks for tracking it down, can you verify that postcss-merge-rules@2.0.5 fixes this issue?

**Comment by tomat** [comment]
@ben-eb: Seems fixed! Thanks

**Comment by ben-eb** [comment]
:+1:

**Comment by fdubost** [comment]
It seems to be OK for me too ! Thank you :v:

**Comment by ben-eb** [comment]
Great stuff. :smile:

**Comment by luhmann** [comment]
same here. thx!

**Comment by DylanPiercey** [comment]
@ben-eb thanks for the quick fix!
