### ISSUE TITLE
Unable to parse color

### ISSUE THREAD

**Issue by dfcreative** [ben-eb/cssnano#19]
Hello!
I have index.css:
```css
body {
	background: hsla(210.0, 6.0%, 0%, 1.0);
}
```
```
$ cssnano index.css
/usr/local/lib/node_modules/cssnano/node_modules/postcss/lib/lazy-result.js:194
            throw error;
                  ^
Error: Unable to parse color from string "hsla(210.0, 6.0%, 0%, 1.0)"
    at Object.Color (/usr/local/lib/node_modules/cssnano/node_modules/postcss-colormin/node_modules/color/index.js:31:15)
    at Color (/usr/local/lib/node_modules/cssnano/node_modules/postcss-colormin/node_modules/color/index.js:7:41)
    at colormin (/usr/local/lib/node_modules/cssnano/node_modules/postcss-colormin/node_modules/colormin/index.js:20:17)
    at Array.map (native)
    at /usr/local/lib/node_modules/cssnano/node_modules/postcss-colormin/index.js:12:34
    at Array.map (native)
    at eachVal (/usr/local/lib/node_modules/cssnano/node_modules/postcss-colormin/index.js:11:31)
    at /usr/local/lib/node_modules/cssnano/node_modules/postcss-colormin/index.js:19:26
    at /usr/local/lib/node_modules/cssnano/node_modules/postcss/lib/container.js:126:34
    at /usr/local/lib/node_modules/cssnano/node_modules/postcss/lib/container.js:104:26
```

**Comment by ben-eb** [comment]
Thanks for reporting. This seems to be an issue with the color module - perhaps it is failing to parse the trailing decimal places? Could you open an over there? https://github.com/harthur/color/issues
