### ISSUE TITLE
Error during reducing steps: TypeError reduceTimingFunctions.js:37:59

### ISSUE THREAD

**Issue by perzek** [ben-eb/cssnano#194]
Since 3.6.0 I'm getting:
`Module build failed: TypeError: Cannot read property 'value' of undefined
    at reduce (/node_modules/cssnano/dist/lib/reduceTimingFunctions.js:37:59)
    at walk (/node_modules/postcss-value-parser/lib/walk.js:7:22)
    at ValueParser.walk (/node_modules/postcss-value-parser/lib/index.js:18:5)
    at /node_modules/cssnano/dist/lib/reduceTimingFunctions.js:65:72`

There was a fix in 3.6.1 but this is different place.

**Comment by ben-eb** [comment]
Fixed in `3.6.2`, thanks for reporting. 👍
