### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by karantin2020** [ben-eb/cssnano#22]
Error is
```
at /home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/cssnext/node_modules/cssnano/lib/core.js:54:52
        at /home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:119:34
        at /home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:104:26
        at Rule.each (/home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:91:22)
        at Rule.eachInside (/home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:103:21)
        at /home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:107:32
        at Root.each (/home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:91:22)
        at Root.eachInside (/home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:103:21)
        at Root.eachDecl (/home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/postcss-loader/node_modules/postcss/lib/container.js:117:25)
        at /home/allecs/Workspace/WebDesign/github.repos/react-isomorphic/node_modules/cssnext/node_modules/cssnano/lib/core.js:20:13
```
Css:
```
/* custom properties */
:root {
--fontSize: 1rem;
--mainColor: #12345678;
--highlightColor: hwb(190, 45%, 40%);
}

.root {

  border: 1px solid red;
  padding: 10px 10px;
  margin:  10px 10px;
  font-size: var(--fontSize);
  line-height: calc(var(--fontSize) * 1.5);
  color: var(--highlightColor);
  text-align: center;
  margin-left: auto;
  margin-right: auto;
  width: 50%;

}
/* TEST SECTION FOR POSTCSS */
/* CSSNEXT */
@custom-selector --heading h1, h2, h3, h4, h5, h6;
--heading { margin-top: 0 }

:fullscreen a {
    transition: transform 1s;
}

/* POSTCSS-MIXINS */
@define-mixin icon $network, $color: blue {
    .icon.is-$(network) {
        color: $color;
        @mixin-content;
    }
    .icon.is-$(network):hover {
        color: white;
        background: $color;
    }
}

@mixin icon twitter {
    background: yellow;
}
@mixin icon youtube, red {
    background: grey;
}

/* POSTCSS-NESTED */
.phone {
    &_title {
        width: 500px;
        @media (width<=500px) {
            width: auto;
        }
        body.is_dark & {
            color: white;
        }
    }
    img {
        display: block;
    }
}

/* POSTCSS-SIMPLE-VARS */
$blue: #056ef0;
$column: 200px;

.menu {
    width: calc(4 * $column);
}
.menu_link {
    background: $blue;
    width: $column;
}

/* POSTCSS-IMPORT */
@import "../style_constants/colors.css";
.barz {color: $bluen;}

/* POSTCSS-CONDITIONALS */
.foo {
  @if 3 < 5 {
    background: green;
  }
  @else {
    background: blue;
  }
}

/* POSTCSS-GRID */
.element {
  grid-column: 1/12 !last;
}
.push {
  grid-push: 1/12;
}
.pull {
  grid-pull: 1/12;
}
.element1 {
  width: grid-width(1/12);
  margin-left: grid-gutter(12);
}

/* POSTCSS-NEAT */
```

Build it with webpack postcss.
```
postcss: [
            postcssMixins, 
            postcssNested, 
            postcssConditionals, 
            postcssImport,
            postcssSimpleVars, 
            cssnext({compress:true}), 
            postcssGrid
  ],
```
Default webpack plugin webpack.optimize compresses it well.
Help please

**Comment by ben-eb** [comment]
Could you do me a favour and run the CSS through this transform and put the result here?

```js
postcss: [
            postcssMixins, 
            postcssNested, 
            postcssConditionals, 
            postcssImport,
            postcssSimpleVars, 
            cssnext({compress:false})
  ],
```

**Comment by karantin2020** [comment]
It builds well with your config. But I need to compress result css file with cssnano in postcss-cssnext.
It needs 'cssnext({compress:true})'. But it passes error

**Comment by ben-eb** [comment]
I ask because I wanted to see if that output file would run through cssnano standalone, or if it was a hole in the AST.

**Comment by karantin2020** [comment]
That is the build result with your config:
```
/* custom properties */

.Main__root {

  border: 1px solid red;
  padding: 10px 10px;
  margin:  10px 10px;
  font-size: 16px;
  font-size: 1rem;
  line-height: 24px;
  line-height: 1.5rem;
  color: rgb(115, 147, 153);
  text-align: center;
  margin-left: auto;
  margin-right: auto;
  width: 50%;

}
/* TEST SECTION FOR POSTCSS */
/* CSSNEXT */
h1,
h2,
h3,
h4,
h5,
h6 { margin-top: 0 }

:-webkit-full-screen a {
    -webkit-transition: -webkit-transform 1s;
            transition: transform 1s;
}

:-moz-full-screen a {
    transition: transform 1s;
}

:-ms-fullscreen a {
    transition: transform 1s;
}

:fullscreen a {
    -webkit-transition: -webkit-transform 1s;
            transition: transform 1s;
}

/* POSTCSS-MIXINS */

.Main__icon.Main__is-twitter {

  color: blue;

  background: yellow;

}

.Main__icon.Main__is-twitter:hover {

  color: white;

  background: blue;

}
.Main__icon.Main__is-youtube {

  color: red;

  background: grey;

}
.Main__icon.Main__is-youtube:hover {

  color: white;

  background: red;

}

/* POSTCSS-NESTED */
.Main__phone_title {

  width: 500px;

}
@media (max-width: 500px) {

  .Main__phone_title {

    width: auto;

  }

}
body.Main__is_dark .Main__phone_title {

  color: white;

}
.Main__phone img {

  display: block;

}

/* POSTCSS-SIMPLE-VARS */

.Main__menu {
    width: 800px;
}
.Main__menu_link {
    background: #056ef0;
    width: 200px;
}

/* POSTCSS-IMPORT */
.Main__mega {display: block;}
.Main__barz {color: #056cf0;}

/* POSTCSS-CONDITIONALS */
.Main__foo {
  background: green
}

/* POSTCSS-GRID */
.Main__element {
  grid-column: 1/12 !last;
}
.Main__push {
  grid-push: 1/12;
}
.Main__pull {
  grid-pull: 1/12;
}
.Main__element1 {
  width: grid-width(1/12);
  margin-left: grid-gutter(12);
}

/* POSTCSS-NEAT */
```

**Comment by magsout** [comment]
Why use PostCSS Import and cssnext both ? Import is already include in cssnext. Plus, I think it's better to use cssnext first and add other plugin after.

**Comment by karantin2020** [comment]
I use postcss-loader and add into it cssnext as postcss-plugin. Cssnext doesn't contain rules to build some hooks. Thats why I use 
```
  postcssMixins, 
  postcssNested, 
  postcssConditionals, 
  postcssSimpleVars, 
```
Postcss-import I used to check is it the import error. Yes it is not needed here :)

**Comment by ben-eb** [comment]
Yep, it builds fine. I think the problem might be a hole in the AST; the error is that `decl.before` does not exist. @ai What do you think of resetting `decl.before` to an empty string here? https://github.com/postcss/postcss/blob/master/lib/node.js#L326-L327

**Comment by ai** [comment]
@ben-eb `undefined` and empty string are very different values ;). If `before` is `undefined` PostCSS will  try to autodetect it by other CSS code.

**Comment by karantin2020** [comment]
Tried to make changes as you write and nothing happen again. There is the same error

**Comment by ben-eb** [comment]
@ai Yes. But cssnano does not fail on this code:

```css
h1{color:red}
```

I can always wrap the offending line with `if (decl.before) {}`. But IMO it should be PostCSS's responsibility to provide `decl.before` always, because when the CSS is parsed, that property is set (even if it is an empty string). So if I have to write that `if` wrapper, it means that every plugin that uses `decl.before` has to have that check.

@karantin2020 Can you update `lib/core.js` in your cssnano installation to have this line and see if that works?

```js
// Remove extra semicolons and whitespace before the declaration
if (declaration.before) {
  declaration.before = declaration.before.replace(/[;\s]/g, '');
}
```

**Comment by karantin2020** [comment]
Found the place in css where error raises:
```
/* POSTCSS-MIXINS */

.Main__icon.Main__is-twitter {

  color: blue;

  background: yellow;

}

.Main__icon.Main__is-twitter:hover {

  color: white;

  background: blue;

}
.Main__icon.Main__is-youtube {

  color: red;

  background: grey;

}
.Main__icon.Main__is-youtube:hover {

  color: white;

  background: red;

}

/* POSTCSS-NESTED */
.Main__phone_title {

  width: 500px;

}
@media (max-width: 500px) {

  .Main__phone_title {

    width: auto;

  }

}
body.Main__is_dark .Main__phone_title {

  color: white;

}
.Main__phone img {

  display: block;

}
```

Both POSTCSS-NESTED and POSTCSS-MIXINS partes give error, separate and together.
Problem is that only cssnano gives error. Postcss builds it well. Webpack.optimize compress it well too.

**Comment by ai** [comment]
@ben-eb if you want to always get a string, use `.style('before')`. It will autodetect `before` by other nodes if it is empty (but it is not so fast).

Here is Autoprefixer example: https://github.com/postcss/autoprefixer-core/blob/9438047307f984b107cba12c5d61570213352dbd/lib/declaration.coffee#L35

**Comment by karantin2020** [comment]
@ben-eb Yes. You are right. This fix helped:
```
if (declaration.before) {
  declaration.before = declaration.before.replace(/[;\s]/g, '');
}
```
in cssnano/lib/core.js.
That is the output:
```
.Main__root{border:1px solid red;padding:10px;margin:10px;font-size:1pc;font-size:1rem;line-height:24px;line-height:1.5rem;color:#739399;text-align:center;margin-left:auto;margin-right:auto;width:50%}h1,h2,h3,h4,h5,h6{margin-top:0}:-webkit-full-screen a{-webkit-transition:-webkit-transform 1s;transition:transform 1s}:-moz-full-screen a{transition:transform 1s}:-ms-fullscreen a{transition:transform 1s}:fullscreen a{-webkit-transition:-webkit-transform 1s;transition:transform 1s}.Main__icon.Main__is-twitter{color:blue;background:#ff0}.Main__icon.Main__is-twitter:hover{color:#fff;background:blue}.Main__icon.Main__is-youtube{color:red;background:grey}.Main__icon.Main__is-youtube:hover{color:#fff;background:red}.Main__phone_title{width:500px}@media (max-width:500px){.Main__phone_title{width:auto}}body.Main__is_dark .Main__phone_title{color:#fff}.Main__phone img{display:block}.Main__menu{width:50pc}.Main__menu_link{background:#056ef0;width:200px}.Main__mega{display:block}.Main__barz{color:#056cf0}.Main__foo{background:green}.Main__element{float:left;width:6.42361%}.Main__push{margin-left:8.50694%}.Main__pull{margin-right:8.50694%}.Main__element1{width:6.42361%;margin-left:2.08333%}
```

**Comment by ben-eb** [comment]
Awesome. I'll publish a fix for this now.

**Comment by karantin2020** [comment]
Hare is interesting result of build process:
webpack.optimize
```
bundle-e70c12e519e6dff784ed.css  1.15 kB
```
cssnano
```
bundle.css  1.19 kB
```
webpack.optimize + cssnano
```
bundle-e70c12e519e6dff784ed.css  1.15 kB
```

That they are.
Cssnano:
```
.Main__root{border:1px solid red;padding:10px;margin:10px;font-size:1pc;font-size:1rem;line-height:24px;line-height:1.5rem;color:#739399;text-align:center;margin-left:auto;margin-right:auto;width:50%}h1,h2,h3,h4,h5,h6{margin-top:0}:-webkit-full-screen a{-webkit-transition:-webkit-transform 1s;transition:transform 1s}:-moz-full-screen a{transition:transform 1s}:-ms-fullscreen a{transition:transform 1s}:fullscreen a{-webkit-transition:-webkit-transform 1s;transition:transform 1s}.Main__icon.Main__is-twitter{color:blue;background:#ff0}.Main__icon.Main__is-twitter:hover{color:#fff;background:blue}.Main__icon.Main__is-youtube{color:red;background:grey}.Main__icon.Main__is-youtube:hover{color:#fff;background:red}.Main__phone_title{width:500px}@media (max-width:500px){.Main__phone_title{width:auto}}body.Main__is_dark .Main__phone_title{color:#fff}.Main__phone img{display:block}.Main__menu{width:50pc}.Main__menu_link{background:#056ef0;width:200px}.Main__mega{display:block}.Main__barz{color:#056cf0}.Main__foo{background:green}.Main__element{float:left;width:6.42361%}.Main__push{margin-left:8.50694%}.Main__pull{margin-right:8.50694%}.Main__element1{width:6.42361%;margin-left:2.08333%}
```

And webpack.optimize:
```
.Main__mega,.Main__phone img{display:block}.Main__root{border:1px solid red;padding:10px;margin:10px auto;font-size:1pc;font-size:1rem;line-height:24px;line-height:1.5rem;color:#739399;text-align:center;width:50%}h1,h2,h3,h4,h5,h6{margin-top:0}:-webkit-full-screen a{-webkit-transition:-webkit-transform 1s;transition:transform 1s}:-moz-full-screen a{transition:transform 1s}:-ms-fullscreen a{transition:transform 1s}:fullscreen a{-webkit-transition:-webkit-transform 1s;transition:transform 1s}.Main__icon.Main__is-twitter{color:#00f;background:#ff0}.Main__icon.Main__is-twitter:hover{color:#fff;background:#00f}.Main__icon.Main__is-youtube{color:red;background:grey}.Main__icon.Main__is-youtube:hover{color:#fff;background:red}.Main__phone_title{width:500px}@media (max-width:500px){.Main__phone_title{width:auto}}body.Main__is_dark .Main__phone_title{color:#fff}.Main__menu{width:50pc}.Main__menu_link{background:#056ef0;width:200px}.Main__barz{color:#056cf0}.Main__foo{background:green}.Main__element{float:left;width:6.42361%}.Main__push{margin-left:8.50694%}.Main__pull{margin-right:8.50694%}.Main__element1{width:6.42361%;margin-left:2.08333%}
```

Need more optimizations :)

**Comment by ben-eb** [comment]
Yeah, main priority now is fixing this issue https://github.com/ben-eb/postcss-minify-selectors/issues/2 via https://github.com/postcss/postcss-selector-parser :smile:
