### ISSUE TITLE
Cssnano breaks gulp on linux

### ISSUE THREAD

**Issue by cronfy** [ben-eb/cssnano#254]
When requiring ```cssnano``` in ```gulpfile.js```, ```gulp.src()``` crashes:

```
nanotest@layoone ~/tmp/project $ gulp
(node:18708) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[12:53:20] Using gulpfile ~/tmp/project/gulpfile.js
[12:53:20] Starting 'default'...
[12:53:20] 'default' errored after 4.94 ms
[12:53:20] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/home/nanotest/tmp/project/node_modules/glob2base/index.js:9:25)
    at setToBase (/home/nanotest/tmp/project/node_modules/glob2base/index.js:48:12)
    at module.exports (/home/nanotest/tmp/project/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/home/nanotest/tmp/project/node_modules/glob-stream/index.js:34:42)
    at Object.gs.create (/home/nanotest/tmp/project/node_modules/glob-stream/index.js:68:42)
    at Gulp.src (/home/nanotest/tmp/project/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at Gulp.<anonymous> (/home/nanotest/tmp/project/gulpfile.js:5:15)
    at module.exports (/home/nanotest/tmp/project/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/nanotest/tmp/project/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/nanotest/tmp/project/node_modules/orchestrator/index.js:214:10)
```

Steps to reproduce:

```
# new user

adduser --disabled-password --gecos "" username
su - nanotest



# node

git clone https://github.com/basherpm/basher.git ~/.basher
echo 'export PATH="$HOME/.basher/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(basher init -)"' >> ~/.bash_profile

. ~/.bash_profile

basher install isaacs/nave

nave use stable

npm install --global npm
npm install --global gulp-cli




# project

cd 
mkdir tmp
cd tmp
mkdir project
cd project
mkdir src css
echo "h1 { font-weight: bold }" > src/style.css

cat << EOF > package.json
{
  "name": "project",
  "version": "1.0.0",
  "description": "Test gulp-cssnano",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "cssnano": "^3.7.4",
    "gulp": "^3.9.1"
  }
}
EOF

npm install

cat << EOF > gulpfile.js
var gulp = require('gulp');
var cssnano = require('cssnano');

gulp.task('default', function() {
  return gulp.src('src/*.css');
});
EOF


# run

gulp
```

See also: ben-eb/gulp-cssnano/issues/54

**Comment by ben-eb** [comment]
Is this related to the security issue that we had to patch for postcss-calc? https://github.com/redhivesoftware/math-expression-evaluator/pull/2

Try a reinstall and see if this helps. 😄
