### ISSUE TITLE
Option "safe: true" with Webpack 2 returns 'FS.readFileSync is not a function'

### ISSUE THREAD

**Issue by CinKon** [ben-eb/cssnano#343]
First: really love cssnano! ;)

Problem: I upgraded a project from Webpack 1.x to Webpack 2.2.0-rc.7.
using cssnano like `require('cssnano')({safe: true})` resolves in a console.error:

```bash
Uncaught TypeError: FS.readFileSync is not a function
    at module.exports (eval at <anonymous> (http://localhost:4000/app.js:12672:1), <anonymous>:31:48)
    at new module.exports (eval at <anonymous> (http://localhost:4000/app.js:12665:1), <anonymous>:21:19)
    at eval (eval at <anonymous> (http://localhost:4000/app.js:12369:1), <anonymous>:95:16)
    at Object.creator [as postcssSvgo] (eval at <anonymous> (http://localhost:4000/app.js:729:1), <anonymous>:150:35)
    at eval (eval at <anonymous> (http://localhost:4000/app.js:9166:1), <anonymous>:295:40)
    at Array.forEach (native)
    at eval (eval at <anonymous> (http://localhost:4000/app.js:9166:1), <anonymous>:282:29)
    at creator (eval at <anonymous> (http://localhost:4000/app.js:729:1), <anonymous>:150:35)
    at eval (eval at <anonymous> (http://localhost:4000/app.js:3227:1), <anonymous>:26:187)
    at Object.<anonymous> (http://localhost:4000/app.js:3227:1)
```

This comes from the `svgo/lib/svgo/config.js`, but I don't know where to start to debug...

**Comment by ben-eb** [comment]
Hi @CinKon,

Are you trying to run cssnano client side? If so, you'll have to tell webpack not to load the `fs` module;

https://github.com/ben-eb/cssnano/blob/master/src/__tests__/_webpack.config.js#L20-L23

**Comment by CinKon** [comment]
Yeah, was a mistake of mine. Included a config, config included package.json, package.json included ALL dependencies... 🙄
