### ISSUE TITLE
Problems with `cssnano.config.js` in v4

### ISSUE THREAD

**Issue by evilebottnawi** [ben-eb/cssnano#375]
My config:
```js
'use strict';

module.exports = {
    preset: [
        'default',
        {
            discardComments: {
                removeAll: true
            }
        }
    ]
};
```

Using cssnano v4 output error:
```shell
TypeError: Cannot read property 'plugins' of undefined
    at resolvePreset (/path/to/node_modules/cssnano/dist/index.js:84:15)
    at /path/to/node_modules/cssnano/dist/index.js:122:16
```

**Comment by ben-eb** [comment]
The fix for this has been released in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.1.
