### ISSUE TITLE
Error in postcss-minify-selectors

### ISSUE THREAD

**Issue by lexich** [ben-eb/cssnano#39]
`"cssnano": "^2.1.1",`
```sh
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'length' of undefined
    at Object.split (/Users/xxxx/node_modules/postcss/lib/list.js:15:35)
    at comma (/Users/xxxx/node_modules/postcss/lib/list.js:56:21)
    at uniq (/Users/xxxx/node_modules/cssnano/node_modules/postcss-minify-selectors/index.js:13:27)
    at optimiseAtRule (/Users/xxxx/node_modules/cssnano/node_modules/postcss-minify-selectors/index.js:21:29)
    at /Users/xxxx/node_modules/postcss/lib/container.js:152:34
    at /Users/xxxx/node_modules/postcss/lib/container.js:102:26
    at Root.each (/Users/xxxx/node_modules/postcss/lib/container.js:89:22)
    at Root.eachInside (/Users/xxxx/node_modules/postcss/lib/container.js:101:21)
    at Root.eachAtRule (/Users/xxxx/node_modules/postcss/lib/container.js:150:25)
    at /Users/xxxx/node_modules/cssnano/node_modules/postcss-minify-selectors/index.js:108:13
```
https://github.com/jonathantneal/postcss-font-magician/issues/3

**Comment by lexich** [comment]
I research problem and find integration problem with https://github.com/jonathantneal/postcss-font-magician plugin. But I thing postcss-minify-selectors needs additional checks `uniq` function.

**Comment by TrySound** [comment]
@lexich Try to replace cssnano with postcss-minify-selectors to locate problem.

**Comment by TrySound** [comment]
@lexich Try to replace cssnano with postcss-minify-selectors, please.

**Comment by ben-eb** [comment]
Could you attach a CSS test case so that I could reproduce this error?

**Comment by lexich** [comment]
in.css
```css
body {
  font: 100%/1.25 'Open Sans', sans-serif;
  background: #F6F5F4;
  overflow-x: hidden;
}
```
index.js
```js
var fs = require("fs");
var postcss = require("postcss");
fs.readFile("./in.css", "utf-8", function(err, data){
	postcss([
		require('postcss-font-magician')({ }),
		require('postcss-minify-selectors')
	]).process(data).then(function (result) {
		console.log(result);
		fs.writeFileSync('./out.css', result.css);
	}).catch(console.log);
});
```

```sh
>> node index.js
[TypeError: Cannot read property 'length' of undefined]
```

**Comment by ben-eb** [comment]
Fixed in https://github.com/ben-eb/postcss-minify-selectors/commit/48c1b503fee2ceed5ce1e711a5aaa9edd7376876 (v1.4.4).
