### ISSUE TITLE
Running into issues using Webpack, PostCSS Loader, CSS Nano and CSS property shape-outside

### ISSUE THREAD

**Issue by soluml** [ben-eb/cssnano#83]
When I use the property `shape-outside: circle();` in my stylesheet I'm getting the error below (Windows 10):

    ERROR in ./~/css-loader?localIdentName=[local]__[hash:base64:5]!./~/postcss-loader!./~/sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true!./assets/scss/main/s.scss
    Module build failed: TypeError: Cannot read property 'value' of undefined

        at C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-normalize-url\index.js:46:24

Here's the related project: https://github.com/ben-eb/postcss-normalize-url/blob/master/index.js#L46

I've gone through my webpack config and removed cssnano from the build and everything works fine.  I've also gone through my CSS and only removed the shape-outside line, and that solved the issue, so I've narrowed it down to that line and cssnano.

My guess is that cssnano is trying to evaluate `circle()` as a method instead of a CSS value or that it's trying to treat circle() as the url() value (e.x. `background-image`).  Here's a copy of my postcss object, I'm only using autoprefixer and cssnano at this time. Removing the comments line from cssnano doesn't seem to do anything to fix the issue:

    postcss: function () {
        return [
            autoprefixer({
                browsers: ['last 2 versions', 'ie >= 9']
            }),
            cssnano({
                comments: { removeAll: true }
            })
        ];
    }

**Comment by soluml** [comment]
Here's the full error in case this helps:

     ERROR in ./~/css-loader?localIdentName=[local]__[hash:base64:5]!./~/postcss-loader!./~/sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true!./assets/scss/main/s.scss
    Module build failed: TypeError: Cannot read property 'value' of undefined

        at C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-normalize-url\index.js:46:24
        at walk (C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-value-parser\lib\walk.js:7:22)
        at ValueParser.walk (C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-value-parser\lib\index.js:17:5)
        at transformDecl (C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-normalize-url\index.js:37:42)
        at C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-normalize-url\index.js:80:24
        at C:\users\me\documents\project\node_modules\postcss\lib\container.js:73:26
        at Rule.each (C:\users\me\documents\project\node_modules\postcss\lib\container.js:59:22)
        at Rule.walk (C:\users\me\documents\project\node_modules\postcss\lib\container.js:72:21)
        at C:\users\me\documents\project\node_modules\postcss\lib\container.js:76:32
        at Root.each (C:\users\me\documents\project\node_modules\postcss\lib\container.js:59:22)
        at Root.walk (C:\users\me\documents\project\node_modules\postcss\lib\container.js:72:21)
        at C:\users\me\documents\project\node_modules\cssnano\node_modules\postcss-normalize-url\index.js:78:13
        at LazyResult.run (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:201:20)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:115:37
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27
        at LazyResult.asyncTick (C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:129:15)
        at C:\users\me\documents\project\node_modules\postcss\lib\lazy-result.js:127:27

**Comment by ben-eb** [comment]
Thanks for reporting, a fix was released in postcss-normalize-url 3.0.4. :smile:

**Comment by soluml** [comment]
No problem! Appreciate the fast turnaround!
